### PR TITLE
Runtime install

### PR DESCRIPTION
**Pull request by thechiefn**

### CODE REVIEW

**Comment by thechiefn** [comment]
The idea is to pull in the <latest> version of Tailscale at runtime, and switch the ARG Version from build number to Stable/Unstable.  Then users can select the latest version based on env var on their container

**Comment by deasmi** [comment]
Sorry, I'm not a fan of this idea, it means people will have no idea what version they are running, a restart will just pull latest.

With the instability there is often present in 1.x.0 releases this seems unwise, and is why I don't push those for at least two weeks.

Features will also be enabled, without testing in Unraid, or documentation.

I feel part of the job I'm doing is making sure people have a stable install in Unraid.

**Comment by thechiefn** [comment]
You could let people define via env parameters what version they would like to run, instead of being locked to a version. The code could be modified to support the latest (stable), unstable, and specific versions.

**Comment by deasmi** [comment]
They aren't locked to a version. You can already use deasmi/unraid-tailscale(:latest) to get the latest version I've tested or deasmi/unraid-tailscale:VERSION to get a specific one. 

So an env is just the same, still need to edit the config, no benefit I can see.

I've started trying to publish new versions as soon as they are released and then move latest tag once I'm happy it's stable.

I'm not sure what issue this is trying to solve, there isn't a huge amount of people moaning that they want the new version pushed to them instantly on release.

**Pull request closed without merging**
